# NOTE: Once we are no longer using the default Ruby environment, we should upgrade
# our base container to something more recent.
FROM 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/circleci:2.7.3-node-browsers

USER root
