export const SET_DOCUMENT_SOURCES = 'SET_DOCUMENT_SOURCES';
export const SET_DOCUMENTS = 'SET_DOCUMENTS';
export const SET_MANIFEST_FETCH_ERROR_MESSAGE = 'SET_MANIFEST_FETCH_ERROR_MESSAGE';
export const SET_MANIFEST_FETCH_STATUS = 'SET_MANIFEST_FETCH_STATUS';
export const SET_VETERAN_ID = 'SET_VETERAN_ID';
export const SET_VETERAN_NAME = 'SET_VETERAN_NAME';
export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT';
