export const MANIFEST_FETCH_STATUS_LOADING = 'MANIFEST_FETCH_STATUS_LOADING';
export const MANIFEST_FETCH_STATUS_LISTED = 'MANIFEST_FETCH_STATUS_LISTED';
export const MANIFEST_FETCH_STATUS_DOWNLOADING = 'MANIFEST_FETCH_STATUS_DOWNLOADING';
export const MANIFEST_FETCH_STATUS_COMPLETE = 'MANIFEST_FETCH_STATUS_COMPLETE';
export const MANIFEST_FETCH_STATUS_ERRORED = 'MANIFEST_FETCH_STATUS_ERRORED';
