inherit_from: .rubocop_todo.yml

require:
  - .rubocop/custom_cop/top_level_constants_per_file.rb

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.1
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

Style/GuardClause:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 200

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 30

Style/DoubleNegation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

CustomCop/TopLevelConstantsPerFile:
  Enabled: true
  Include:
    - 'app/**/*'
    - 'lib/**/*'
  Exclude:
    - '**/*[^.rb]' # exclude non-.rb files (ex: .rake files)
