language: ruby
dist: trusty
addons:
  chrome: stable

branches:
    only:
        - master
rvm:
  - 2.3.0

# Install PhantomJS 2.0 from source binary, remove once TravisCI environment has PhantomJS 2.0 installed
# see https://github.com/travis-ci/travis-ci/issues/3225 for more details
before_install:
  - nvm install $(cat .nvmrc)
  - node -v

  # Yarn install instructions from https://yarnpkg.com/en/docs/install#linux-tab
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - ./ci-bin/retry.bash sudo apt-get update
  - sudo apt-get install yarn=1.2.1-1

  # Travis has an old version of yarn installed at /usr/local/bin, and that comes first in the PATH,
  # so we need to explicitly point to the version of Yarn we just installed.
  - export YARN=/usr/bin/yarn
  
  - $YARN --version
# See https://github.com/department-of-veterans-affairs/caseflow/issues/1744 for detail on why we're doing this.
  - wget https://s3-us-gov-west-1.amazonaws.com/dsva-appeals-devops/chromium-chromedriver_53.0.2785.143-0ubuntu0.14.04.1.1145_amd64.deb -O $PWD/chromium-chromedriver.deb
  - sudo dpkg -i $PWD/chromium-chromedriver.deb
  - sudo apt-get install -f
  - sudo apt-get install pdftk
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - cd ./client && $YARN --frozen-lockfile
  - cd ..

  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:schema:load
  - sudo apt-get install pdftk

  # Start up xvfb for headless browser testing
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/
  # - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"
  # - sleep 3 # give xvfb some time to start

script:
  - bundle exec rake

bundler_args: "--deployment --without development"
cache:
  - bundler

notifications:
  email: false

services:
  - redis-server
