language: ruby
dist: trusty

branches:
    only:
        - master
rvm:
  - 2.3.0

# Install PhantomJS 2.0 from source binary, remove once TravisCI environment has PhantomJS 2.0 installed
# see https://github.com/travis-ci/travis-ci/issues/3225 for more details
before_install:
  - mkdir travis-phantomjs
  - wget https://s3-us-west-2.amazonaws.com/va.devops/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
  - phantomjs -v

  - nvm install $(cat .nvmrc)
  - node -v

  # Yarn install instructions from https://yarnpkg.com/en/docs/install#linux-tab
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - ./ci-bin/retry.bash sudo apt-get update
  - sudo apt-get install yarn=1.2.1-1

  # Travis has an old version of yarn installed at /usr/local/bin, and that comes first in the PATH,
  # so we need to explicitly point to the version of Yarn we just installed.
  - export YARN=/usr/bin/yarn
  
  - $YARN --version
  - $YARN --frozen-lockfile

before_script:
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:schema:load
  - sudo apt-get install pdftk

script:
  - bundle exec rake

bundler_args: "--deployment --without development"
cache:
  - bundler

notifications:
  email: false

services:
  - redis-server
