version: '3'
services:
  appeals-redis:
    image: redis:6.2.6
    ports:
      - "16379:6379"

  appeals-postgres:
    image: postgres:14.8
    ports:
      - "5432:5432"
    volumes:
      - "postgresdata:/var/lib/postgresql/data"
    environment:
     - POSTGRES_PASSWORD=postgres

  appeals-localstack-aws:
    image: localstack/localstack:0.12.5
    ports:
      - "4566:4566"
    volumes:
      - ./local/sqs/conf:/conf

volumes:
  postgresdata:
  u01:
  ORCL:
  u02:
