version: '3'
services:
  appeals-redis:
    image: redis:2.8.23
    ports:
      - "16379:6379"

  appeals-postgres:
    image: postgres:9.5
    ports:
      - "15432:5432"
    volumes:
      - "postgresdata:/var/lib/postgresql/data"
    environment:
     - POSTGRES_PASSWORD=postgres

  appeals-localstack-aws:
    image: localstack/localstack
    ports:
      - "14567-14583:4567-4583"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=sqs
      - SQS_PORT_EXTERNAL=14576
    volumes:
      - ./local/sqs/conf:/conf

volumes:
  postgresdata:
  u01:
  ORCL:
  u02:
