#
# developer convenience.
# Copy this file to Makefile and then you can (e.g.):
#
#  % make install
#  % make run
#
#

up:	## Start Docker
	docker-compose up -d

down:	## Stop Docker
	docker-compose down

run: up	## Start Rails
	foreman start

test: clean	## Run the rspec suite
	bundle exec rspec

clean:	## Remove old files
	rm -f log/test.log
	rm -f app/assets/javascripts/*webpack*
	rm -rf tmp/capybara

lint:	## Run the linter
	CI=true bundle exec rake lint

jslint:	## Run the js linter
	cd client && yarn run lint

security:	## Run security task
	bundle exec rake security

check: test lint jslint

logs:	## Follow the Docker logs
	docker-compose logs -f

db:	## Connect with psql
	bundle exec rails dbconsole

c:	## Start Rails console
	bundle exec rails console

migrate:	## Run pending migrations
	bundle exec rake db:migrate

rollback:	## Rollback last migration
	bundle exec rake db:rollback

reset:	## Reset the db
	bundle exec rake db:reset

install:	## bundle/yarn install dependencies
	bundle check || bundle install
	cd client && yarn

update: fresh install migrate

# Self-documented makefile from https://marmelab.com/blog/2016/02/29/auto-documented-makefile.html
help:  ## Shows help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

.PHONY: test run clean lint jslint check logs db update security install reset migrate rollback c
