development:
  adapter: async

test:
  adapter: async # test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: caseflow_efolder_production
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>