default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_CONN_POOL_MAX_SIZE"] || 5 %>
  timeout: 5000

default: &default_local
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] || `whoami` %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  <<: *default_local
  database: caseflow_efolder_development

staging:
  <<: *default
  <<: *default_local
  database: caseflow_efolder_staging

test:
  <<: *default
  <<: *default_local
  database: caseflow_efolder_test

production:
  <<: *default
  url: <%= ENV["POSTGRES_URL"] %>
