# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_CONN_POOL_MAX_SIZE"] || 5 %>
  timeout: 5000

development:
  <<: *default
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] || `whoami` %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: caseflow_efolder_development

staging:
  <<: *default
  username: <%= `whoami` %>
  database: caseflow_efolder_staging

test:
  <<: *default
  username: <%= ENV['POSTGRES_USER'] || `whoami` %>
  database: caseflow_efolder_test
  host: <%= ENV['POSTGRES_HOST'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  <<: *default
  url: <%= ENV["POSTGRES_URL"] %>
