restart_stalled_downloads_job:
  cron: "*/1 * * * *"
  class: "RestartStalledDownloadsJob"
  queue: default
  active_job: true

calculate_stats_job:
  cron: "*/2 * * * *"
  class: "CalculateStatsJob"
  queue: default
  active_job: true