# Every minute
restart_stalled_downloads_job:
  cron: "*/1 * * * *"
  class: "RestartStalledDownloadsJob"
  queue: default
  active_job: true

# Every 2 minutes
calculate_stats_job:
  cron: "*/2 * * * *"
  class: "CalculateStatsJob"
  queue: default
  active_job: true

# Every night at 3am
clean_download_files_job:
  cron: "0 3 * * * America/New_York"
  class: "CleanDownloadFilesJob"
  queue: default
  active_job: true

# Check for ManifestSources stuck in pending state at the top of every hour during the workday, work week.
calculate_stats_job:
  cron: "0 9-17 * * 1-5"
  class: "AlertStuckManifestSourceJob"
  queue: default
  active_job: true
